-- Run this in Supabase SQL Editor after enabling the vector extension
-- Go to: Database > Extensions > search "vector" > Enable

-- Knowledge base chunks table
CREATE TABLE document_chunks (
  id          TEXT PRIMARY KEY,
  content     TEXT NOT NULL,
  source      TEXT NOT NULL,
  title       TEXT NOT NULL,
  topic       TEXT NOT NULL,
  chunk_index INTEGER NOT NULL,
  embedding   vector(1536),
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- HNSW index (recommended for small datasets ~50-80 chunks)
CREATE INDEX ON document_chunks
  USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- Similarity search function (called via Supabase RPC)
CREATE OR REPLACE FUNCTION match_document_chunks(
  query_embedding vector(1536),
  match_threshold FLOAT DEFAULT 0.3,
  match_count     INT   DEFAULT 5
)
RETURNS TABLE (
  id          TEXT,
  content     TEXT,
  source      TEXT,
  title       TEXT,
  topic       TEXT,
  chunk_index INTEGER,
  similarity  FLOAT
)
LANGUAGE plpgsql AS $$
BEGIN
  RETURN QUERY
  SELECT
    dc.id,
    dc.content,
    dc.source,
    dc.title,
    dc.topic,
    dc.chunk_index,
    1 - (dc.embedding <=> query_embedding) AS similarity
  FROM document_chunks dc
  WHERE 1 - (dc.embedding <=> query_embedding) > match_threshold
  ORDER BY dc.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- Lead captures table
CREATE TABLE leads (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            TEXT,
  email           TEXT NOT NULL,
  company         TEXT,
  trigger_message TEXT NOT NULL,
  conversation    JSONB DEFAULT '[]',
  created_at      TIMESTAMPTZ DEFAULT NOW()
);
